name: android_flutter
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.0
  # https://pub.dev/packages/fish_redux
  fish_redux: ^0.3.6
  # https://pub.dev/packages/dio
  dio: 3.0.10
  # https://pub.dev/packages/fluro
  fluro: ^1.7.8
  # https://pub.flutter-io.cn/packages/fluttertoast
  fluttertoast: ^7.1.8
  # https://pub.dev/packages/shared_preferences
  shared_preferences: ^0.5.12+4
  # https://pub.dev/packages/one_context
  one_context: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  json2entity: 1.0.6

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/images/1.5x/
    - assets/images/2.0x/
    - assets/images/3.0x/
    - assets/images/4.0x/

flutter_intl:
  enabled: true
